# Generated by Django 3.2.3 on 2022-06-06 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Spoilage', 'Spoilage'), ('Others', 'Others')], max_length=32)),
                ('amountTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('qty', models.IntegerField(default=0)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unitCost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('amountTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingReportItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('unitCost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amountTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('qty', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory')),
                ('rr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receivingreport')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('unitCost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amountTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('qty', models.IntegerField()),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adjustment')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory')),
            ],
        ),
    ]
