# Generated by Django 3.2.3 on 2022-06-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customers_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingreport',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.suppliers'),
        ),
    ]
