# Generated by Django 3.2.3 on 2022-07-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220703_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentitems',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjitems', to='app.adjustment'),
        ),
        migrations.AlterField(
            model_name='adjustmentitems',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjitems', to='app.inventory'),
        ),
    ]
