# Generated by Django 3.2.3 on 2022-07-15 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20220705_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateField(null=True)),
                ('total', models.DecimalField(decimal_places=4, max_digits=16)),
                ('subTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vat', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vatExempt', models.DecimalField(decimal_places=4, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('payment', models.DecimalField(decimal_places=4, max_digits=16)),
                ('change', models.DecimalField(decimal_places=4, max_digits=16)),
                ('net', models.DecimalField(decimal_places=4, max_digits=16)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customers')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('unitCost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amountTotal', models.DecimalField(decimal_places=4, max_digits=16)),
                ('qty', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesitems', to='app.inventory')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesitems', to='app.sales')),
            ],
        ),
    ]
