# Generated by Django 3.2.3 on 2022-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='temporaryCustomer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
