# Generated by Django 3.2.3 on 2022-07-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sales_temporarycustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='unitCost',
        ),
    ]
