# Generated by Django 3.2.3 on 2022-07-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
