# Generated by Django 3.2.3 on 2022-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_businessprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
